export interface StaticProduct {
  id: string;
  nameEn: string;
  nameAr: string;
  descriptionEn: string;
  descriptionAr: string;
  category: string;
  featuresEn: string[];
  featuresAr: string[];
  sizes?: string[];
}

export const staticProducts: StaticProduct[] = [
  {
    id: "sp-001",
    nameEn: "Snow Foam Shampoo",
    nameAr: "شامبو الرغوة الثلجية",
    descriptionEn: "High-foaming pre-wash formula that clings to paintwork, loosening dirt and grime before the main wash.",
    descriptionAr: "تركيبة ما قبل الغسيل عالية الرغوة تلتصق بالطلاء وتزيل الأوساخ قبل الغسيل الرئيسي.",
    category: "Shampoos",
    featuresEn: ["High-Foam", "pH Neutral", "Pre-Wash"],
    featuresAr: ["رغوة عالية", "متعادل الحموضة", "ما قبل الغسيل"],
    sizes: ["100ml", "200ml", "400ml"],
  },
  {
    id: "sp-002",
    nameEn: "Pure Glide Pre-Wash Shampoo",
    nameAr: "شامبو غسيل مسبق Pure Glide",
    descriptionEn: "Lubricating pre-wash shampoo that creates a protective slip layer for safe, scratch-free washing.",
    descriptionAr: "شامبو غسيل مسبق مزلق يخلق طبقة انزلاق واقية للغسيل الآمن الخالي من الخدش.",
    category: "Shampoos",
    featuresEn: ["Lubricating", "Scratch-Free", "Wax Safe"],
    featuresAr: ["مزلق", "خالٍ من الخدش", "آمن مع الشمع"],
    sizes: ["500ml", "1L"],
  },
  {
    id: "sp-003",
    nameEn: "Spray Detailer & Wax",
    nameAr: "إسبري تلميع وشمع",
    descriptionEn: "Quick-use spray wax that adds deep gloss and protection in seconds. Perfect for between-wash top-ups.",
    descriptionAr: "شمع إسبري سريع الاستخدام يضيف لمعاناً عميقاً وحماية في ثوانٍ.",
    category: "Polishing",
    featuresEn: ["Spray-On", "UV Protection", "Quick Dry"],
    featuresAr: ["تطبيق بالإسبري", "حماية UV", "جفاف سريع"],
    sizes: ["500ml"],
  },
  {
    id: "sp-004",
    nameEn: "Gloss Pro Detailer Wax",
    nameAr: "شمع تلميع احترافي Gloss Pro",
    descriptionEn: "Professional liquid wax for a deep mirror-finish gloss. Fortified with carnauba for lasting protection.",
    descriptionAr: "شمع سائل احترافي للمسة لامعة كالمرآة. مدعم بالكارناوبا للحماية الدائمة.",
    category: "Polishing",
    featuresEn: ["Carnauba Formula", "Mirror Finish", "Long-Lasting"],
    featuresAr: ["تركيبة كارناوبا", "لمسة مرآة", "طويلة الأمد"],
    sizes: ["250ml", "500ml"],
  },
  {
    id: "sp-005",
    nameEn: "Quick Detailer & Wax 2-in-1",
    nameAr: "مُلمِّع وشمع 2 في 1",
    descriptionEn: "Dual-action formula that cleans and waxes in a single step. Ideal for quick maintenance between full details.",
    descriptionAr: "تركيبة ثنائية المفعول تنظف وتشمع في خطوة واحدة.",
    category: "Polishing",
    featuresEn: ["2-in-1 Action", "Time-Saving", "Streak-Free"],
    featuresAr: ["مفعول 2 في 1", "موفر للوقت", "خالٍ من الخطوط"],
    sizes: ["500ml"],
  },
  {
    id: "sp-006",
    nameEn: "Glass Cleaner",
    nameAr: "منظف زجاج",
    descriptionEn: "Streak-free formula for crystal-clear windows and mirrors inside and out. Safe on all tinted glass.",
    descriptionAr: "تركيبة خالية من الخطوط للنوافذ والمرايا الشفافة من الداخل والخارج.",
    category: "Glass Care",
    featuresEn: ["Streak-Free", "Tint Safe", "Fast-Acting"],
    featuresAr: ["خالٍ من الخطوط", "آمن للتلوين", "سريع المفعول"],
    sizes: ["500ml", "1L"],
  },
  {
    id: "sp-007",
    nameEn: "Interior Cleaner",
    nameAr: "منظف داخلي",
    descriptionEn: "Gentle yet powerful cleaner for dashboards, trim, fabric seats, and all interior plastics.",
    descriptionAr: "منظف لطيف وفعال لألواح القيادة والزخارف والمقاعد القماشية.",
    category: "Interior Care",
    featuresEn: ["Multi-Surface", "Anti-Static", "Fresh Scent"],
    featuresAr: ["متعدد الأسطح", "مضاد للكهرباء", "رائحة منعشة"],
    sizes: ["500ml", "1L"],
  },
  {
    id: "sp-008",
    nameEn: "All Purpose Dressing",
    nameAr: "صبغ متعدد الأغراض",
    descriptionEn: "Premium dressing for tyres, rubber trims, and vinyl. Restores deep black finish without greasiness.",
    descriptionAr: "صبغ فاخر للكفرات والمطاط والفينيل. يعيد اللون الأسود العميق دون دهونة.",
    category: "Interior Care",
    featuresEn: ["Non-Greasy", "Deep Black", "Versatile"],
    featuresAr: ["غير دهني", "أسود عميق", "متعدد الاستخدامات"],
    sizes: ["500ml"],
  },
  {
    id: "sp-009",
    nameEn: "Leather Conditioner",
    nameAr: "مرطب جلد",
    descriptionEn: "Nourishing conditioner that moisturises, softens, and protects leather against cracking in Qatar's dry heat.",
    descriptionAr: "مرطب مغذٍ يرطب ويلين ويحمي الجلد من التشقق في حرارة قطر.",
    category: "Interior Care",
    featuresEn: ["UV Protectant", "Anti-Crack", "Softening"],
    featuresAr: ["واقٍ من UV", "مضاد للتشقق", "ملين"],
    sizes: ["250ml", "500ml"],
  },
  {
    id: "sp-010",
    nameEn: "Super Max Degreaser",
    nameAr: "مزيل دهون Super Max",
    descriptionEn: "Heavy-duty concentrated degreaser for engines, undercarriages, and heavily contaminated surfaces.",
    descriptionAr: "مزيل دهون مركز عالي الكفاءة للمحركات والأسطح الملوثة بشدة.",
    category: "Multi-Purpose",
    featuresEn: ["Concentrated", "Heavy-Duty", "Biodegradable"],
    featuresAr: ["مركز", "عالي الكفاءة", "قابل للتحلل"],
    sizes: ["1L", "5L"],
  },
  {
    id: "sp-011",
    nameEn: "Road Ready Wheel & Tire Cleaner",
    nameAr: "منظف جنوط وكفرات Road Ready",
    descriptionEn: "Powerful acid-free formula that dissolves brake dust, road grime, and contamination from alloy wheels.",
    descriptionAr: "تركيبة قوية خالية من الأحماض تذيب غبار الفرامل وأوساخ الطريق.",
    category: "Tire Care",
    featuresEn: ["Acid-Free", "Brake Dust Removal", "Safe for Alloys"],
    featuresAr: ["خالٍ من الأحماض", "إزالة غبار الفرامل", "آمن للجنوط"],
    sizes: ["500ml", "1L"],
  },
  {
    id: "sp-012",
    nameEn: "Quick Renew Rubber & Plastic Restorer",
    nameAr: "مجدد مطاط وبلاستيك Quick Renew",
    descriptionEn: "Restores faded exterior plastics and rubber to factory-new appearance with long-lasting UV protection.",
    descriptionAr: "يجدد البلاستيك والمطاط الخارجي المتلاشي لمظهر جديد كالمصنع.",
    category: "Tire Care",
    featuresEn: ["UV Barrier", "Fade Restoration", "Long-Lasting"],
    featuresAr: ["حاجز UV", "استعادة اللون", "طويل الأمد"],
    sizes: ["250ml", "500ml"],
  },
  {
    id: "sp-013",
    nameEn: "Tire Shine",
    nameAr: "لامع كفرات",
    descriptionEn: "Long-lasting water-based tyre shine that gives a deep wet-look gloss without sling or greasiness.",
    descriptionAr: "لامع كفرات مائي طويل الأمد يعطي لمعاناً عميقاً بمظهر مبلل دون انتشار.",
    category: "Tire Care",
    featuresEn: ["No-Sling", "Water-Based", "Wet-Look Gloss"],
    featuresAr: ["بدون انتشار", "مائي", "لمعان مبلل"],
    sizes: ["500ml", "1L"],
  },
];

export const staticCategories = [
  { id: "all",           nameEn: "All Products",          nameAr: "جميع المنتجات" },
  { id: "Shampoos",      nameEn: "Shampoos & Washing",     nameAr: "الشامبوهات والغسيل" },
  { id: "Polishing",     nameEn: "Polishing & Waxing",     nameAr: "التلميع والشمع" },
  { id: "Glass Care",    nameEn: "Glass Care",             nameAr: "عناية الزجاج" },
  { id: "Interior Care", nameEn: "Interior Care",          nameAr: "العناية الداخلية" },
  { id: "Multi-Purpose", nameEn: "Multi-Purpose Cleaners", nameAr: "منظفات متعددة الأغراض" },
  { id: "Tire Care",     nameEn: "Tire Care",              nameAr: "عناية الكفرات" },
];
